#!/usr/bin/env bash
# make_field_report.sh
# Opera Numerorum -- Generate 1pp and 2pp Field Report variants in one step.
# Runs build_field_report.py twice, prints both SHAs, updates invariants.json.
#
# Usage:
#   bash make_field_report.sh
# or via Makefile:
#   make field_report

set -e

OUT_1PP="certificates/Field_Report_1pp.pdf"
OUT_2PP="certificates/Field_Report_2pp.pdf"
INVARIANTS="certificates/invariants.json"

echo "=== Building 1pp layout (one photo per page, ~170 pp) ==="
python3 certificates/build_field_report.py --layout 1pp --output "$OUT_1PP"
SHA_1PP=$(sha256sum "$OUT_1PP" | awk '{print $1}')
echo "1pp SHA-256: $SHA_1PP"

echo ""
echo "=== Building 2pp layout (two photos per page, ~85 pp) ==="
python3 certificates/build_field_report.py --layout 2pp --output "$OUT_2PP"
SHA_2PP=$(sha256sum "$OUT_2PP" | awk '{print $1}')
echo "2pp SHA-256: $SHA_2PP"

echo ""
echo "=== Recording SHAs in invariants.json ==="
python3 - <<PYEOF
import json, datetime

path = "$INVARIANTS"
with open(path) as f:
    inv = json.load(f)

inv["field_report_variants"] = {
    "note": "Both layout variants generated by make_field_report.sh in a single step.",
    "generated_utc": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
    "1pp": {
        "output": "$OUT_1PP",
        "sha256_output": "$SHA_1PP",
        "layout": "1pp",
        "photo_width_inches": 6.5,
        "approx_pages": 170
    },
    "2pp": {
        "output": "$OUT_2PP",
        "sha256_output": "$SHA_2PP",
        "layout": "2pp",
        "photo_width_inches": 3.0,
        "approx_pages": 85
    }
}

with open(path, "w") as f:
    json.dump(inv, f, indent=2)

print("invariants.json updated.")
PYEOF

echo ""
echo "=== Summary ==="
printf "1pp  %s\n     SHA-256: %s\n" "$OUT_1PP" "$SHA_1PP"
printf "2pp  %s\n     SHA-256: %s\n" "$OUT_2PP" "$SHA_2PP"
